### PR TITLE
Fix go client broken due to API change; commit Go proto

### PR DESCRIPTION
**Pull request by ramonza**

### CODE REVIEW

**Comment by odeke-em** [comment]
Thanks @ramonza for this followup PR.

So we already have the proto file in https://github.com/census-instrumentation/opencensus-experiments/tree/master/integration/src/main/proto, it was moved there because the Java code needed it in that location. No need to commit it again :)

**Comment by ramonza** [comment]
I added the generated Go file

**Comment by odeke-em** [comment]
>I added the generated Go file

@ramonza it already exists in https://github.com/census-instrumentation/opencensus-experiments/blob/master/integration/src/main/proto/defs.pb.go.
Did you use the Makefile generation directive or was this by hand?

**Comment by ramonza** [comment]
I ran "make test" and it was generated to this location

**Comment by songy23** [comment]
That's weird, I think the generated pb.go should be under src/main/proto/? (https://github.com/census-instrumentation/opencensus-experiments/blob/master/integration/Makefile#L5)

Did you run against the latest Makefile?

**Comment by odeke-em** [comment]
@songy23 the proto directive is broken but in deed, @ramonza it shouldn't generate that file in anyway, unless that's using older code before @songy23's commit. 
@ramonza, please remove that protofile from your commit, I'll send a separate PR to fix that directive and the latest file.

**Comment by songy23** [comment]
I see - BTW all the go files are using the pb.go under src/main/proto, e.g https://github.com/census-instrumentation/opencensus-experiments/blob/master/integration/go-grpc-client/interop_test.go#L31.

**Comment by odeke-em** [comment]
I've sent https://github.com/census-instrumentation/opencensus-experiments/pull/7, sorry for the noise @ramonza.

**Comment by odeke-em** [comment]
With https://github.com/census-instrumentation/opencensus-experiments/pull/7 merged, @ramonza if you remove that *pb.go file in your commit and only have the API usage fix, we'll be gucci.

**Pull request merged**
