### PR TITLE
Restructure Java code.

### PR DESCRIPTION
**Pull request by songy23**
Part of https://github.com/census-instrumentation/opencensus-experiments/issues/17.

Restructure Java code according to @bogdandrutu's suggestion:
- integration/java/grpc/... contains the java implementation for grpc
- integration/java/http/... contains the java implementation for http

EDIT:
Closes https://github.com/census-instrumentation/opencensus-experiments/issues/17.

### CODE REVIEW

**Comment by odeke-em** [comment]
@songy23 might need a rebase from master but otherwise LGTM.

**Comment by songy23** [comment]
Rebased - thanks!

**Comment by bogdandrutu** [comment]
It is probably good to move gradle stuff to java directory. That way the root directory get simplified.

**Comment by songy23** [comment]
Sounds good, I created https://github.com/census-instrumentation/opencensus-experiments/pull/24 to move the gradle files.

**Pull request merged**
