### PR TITLE
Move gradle to java directory.

### PR DESCRIPTION
**Pull request by songy23**
Also re-generated the wrapper files.

### CODE REVIEW

**Comment by songy23** [comment]
Agree we should probably set up travis ci for this repo (though I think it should be a separate PR). Created https://github.com/census-instrumentation/opencensus-experiments/issues/25 to keep track.

**Comment by bogdandrutu** [comment]
Definitely a separate PR. But was hard for me to check that this does not
break.

**Comment by songy23** [comment]
Holding off merging this PR until I have Travis set up.

**Comment by bogdandrutu** [comment]
You can merge this now. Don't have to wait.

**Pull request merged**
